version: "3.6"

services:
  ghp-sync:
    # published on release; `docker compose pull` picks up a new build of this tag
    image: ghcr.io/katbyte/ghp-sync:v0.3.2
    container_name: ghp-sync
    environment:
      - "TZ=America/Vancouver"
      - "SYNC_CRON=0 0,3,6,9,12,15,18,21 * * *"
      - "SYNC_CMD=prs|issues"
      - "GITHUB_TOKEN="
      - "GITHUB_ORG=hashicorp"
      - "GITHUB_REPO=terraform-provider-azurerm"
      - "GITHUB_PROJECT_NUMBER="
      - "GITHUB_AUTHORS="
      - "GITHUB_LABELS="
