---
name: linting
on:
  push:
    branches: [ 'main' ]
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.3.1
          args: -v
